# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculate.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from tkinter import messagebox


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(431, 508)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.number_7 = QtWidgets.QPushButton(self.centralwidget)
        self.number_7.setGeometry(QtCore.QRect(10, 180, 71, 61))
        self.number_7.setStyleSheet("color:#000000;\n"
"font-size:20px;\n"
"background:#00e6b8;")
        self.number_7.setObjectName("number_7")
        self.number_0 = QtWidgets.QPushButton(self.centralwidget)
        self.number_0.setGeometry(QtCore.QRect(90, 390, 71, 61))
        self.number_0.setStyleSheet("color:#000000;\n"
"font-size:20px;\n"
"background:#00e6b8;")
        self.number_0.setObjectName("number_0")
        self.number_3 = QtWidgets.QPushButton(self.centralwidget)
        self.number_3.setGeometry(QtCore.QRect(170, 320, 71, 61))
        self.number_3.setStyleSheet("color:#000000;\n"
"font-size:20px;\n"
"background:#00e6b8;")
        self.number_3.setObjectName("number_3")
        self.number_2 = QtWidgets.QPushButton(self.centralwidget)
        self.number_2.setGeometry(QtCore.QRect(90, 320, 71, 61))
        self.number_2.setStyleSheet("color:#000000;\n"
"font-size:20px;\n"
"background:#00e6b8;")
        self.number_2.setObjectName("number_2")
        self.number_1 = QtWidgets.QPushButton(self.centralwidget)
        self.number_1.setGeometry(QtCore.QRect(10, 320, 71, 61))
        self.number_1.setStyleSheet("color:#000000;\n"
"font-size:20px;\n"
"background:#00e6b8;")
        self.number_1.setObjectName("number_1")
        self.number_6 = QtWidgets.QPushButton(self.centralwidget)
        self.number_6.setGeometry(QtCore.QRect(170, 250, 71, 61))
        self.number_6.setStyleSheet("color:#000000;\n"
"font-size:20px;\n"
"background:#00e6b8;")
        self.number_6.setObjectName("number_6")
        self.number_4 = QtWidgets.QPushButton(self.centralwidget)
        self.number_4.setGeometry(QtCore.QRect(10, 250, 71, 61))
        self.number_4.setStyleSheet("color:#000000;\n"
"font-size:20px;\n"
"background:#00e6b8;")
        self.number_4.setObjectName("number_4")
        self.number_5 = QtWidgets.QPushButton(self.centralwidget)
        self.number_5.setGeometry(QtCore.QRect(90, 250, 71, 61))
        self.number_5.setStyleSheet("color:#000000;\n"
"font-size:20px;\n"
"background:#00e6b8;")
        self.number_5.setObjectName("number_5")
        self.number_9 = QtWidgets.QPushButton(self.centralwidget)
        self.number_9.setGeometry(QtCore.QRect(170, 180, 71, 61))
        self.number_9.setStyleSheet("color:#000000;\n"
"font-size:20px;\n"
"background:#00e6b8;")
        self.number_9.setObjectName("number_9")
        self.number_8 = QtWidgets.QPushButton(self.centralwidget)
        self.number_8.setGeometry(QtCore.QRect(90, 180, 71, 61))
        self.number_8.setStyleSheet("color:#000000;\n"
"font-size:20px;\n"
"background:#00e6b8;")
        self.number_8.setObjectName("number_8")
        self.point_btn = QtWidgets.QPushButton(self.centralwidget)
        self.point_btn.setGeometry(QtCore.QRect(170, 390, 71, 61))
        self.point_btn.setStyleSheet(" color:#000000;\n"
"font-size:20px;\n"
"background-color:#33cc33;")
        self.point_btn.setObjectName("point_btn")
        self.number_00 = QtWidgets.QPushButton(self.centralwidget)
        self.number_00.setGeometry(QtCore.QRect(10, 390, 71, 61))
        self.number_00.setStyleSheet("color:#000000;\n"
"font-size:20px;\n"
"background:#00e6b8;")
        self.number_00.setObjectName("number_00")
        self.equal_btn = QtWidgets.QPushButton(self.centralwidget)
        self.equal_btn.setGeometry(QtCore.QRect(250, 390, 161, 61))
        self.equal_btn.setStyleSheet("color:white;\n"
"font-size:20px;\n"
"background-color:#008000;")
        self.equal_btn.setObjectName("equal_btn")
        self.plus_btn = QtWidgets.QPushButton(self.centralwidget)
        self.plus_btn.setGeometry(QtCore.QRect(250, 320, 71, 61))
        self.plus_btn.setStyleSheet(" color:#000000;\n"
"font-size:20px;\n"
"background-color:#33cc33;")
        self.plus_btn.setObjectName("plus_btn")
        self.subtraction_btn = QtWidgets.QPushButton(self.centralwidget)
        self.subtraction_btn.setGeometry(QtCore.QRect(340, 320, 71, 61))
        self.subtraction_btn.setStyleSheet(" color:#000000;\n"
"font-size:20px;\n"
"background-color:#33cc33;")
        self.subtraction_btn.setObjectName("subtraction_btn")
        self.division_btn = QtWidgets.QPushButton(self.centralwidget)
        self.division_btn.setGeometry(QtCore.QRect(340, 250, 71, 61))
        self.division_btn.setStyleSheet(" color:#000000;\n"
"font-size:20px;\n"
"background-color:#33cc33;")
        self.division_btn.setObjectName("division_btn")
        self.multiplication_btn = QtWidgets.QPushButton(self.centralwidget)
        self.multiplication_btn.setGeometry(QtCore.QRect(250, 250, 71, 61))
        self.multiplication_btn.setStyleSheet(" color:#000000;\n"
"font-size:20px;\n"
"background-color:#33cc33;")
        self.multiplication_btn.setObjectName("multiplication_btn")
        self.clear_btn = QtWidgets.QPushButton(self.centralwidget)
        self.clear_btn.setGeometry(QtCore.QRect(250, 180, 161, 61))
        self.clear_btn.setStyleSheet(" color:#000000;\n"
"font-size:20px;\n"
"background-color:#33cc33;")
        self.clear_btn.setObjectName("clear_btn")
        self.back_btn = QtWidgets.QPushButton(self.centralwidget)
        self.back_btn.setGeometry(QtCore.QRect(340, 110, 71, 61))
        self.back_btn.setStyleSheet(" color:#000000;\n"
"font-size:20px;\n"
"background-color:#33cc33;")
        self.back_btn.setObjectName("back_btn")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 110, 331, 61))
        self.lineEdit.setStyleSheet("color:#000000;\n"
"font-size:24px;\n"
"")
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 431, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.number_7.setText(_translate("MainWindow", "7"))
        self.number_0.setText(_translate("MainWindow", "0"))
        self.number_3.setText(_translate("MainWindow", "3"))
        self.number_2.setText(_translate("MainWindow", "2"))
        self.number_1.setText(_translate("MainWindow", "1"))
        self.number_6.setText(_translate("MainWindow", "6"))
        self.number_4.setText(_translate("MainWindow", "4"))
        self.number_5.setText(_translate("MainWindow", "5"))
        self.number_9.setText(_translate("MainWindow", "9"))
        self.number_8.setText(_translate("MainWindow", "8"))
        self.point_btn.setText(_translate("MainWindow", "."))
        self.number_00.setText(_translate("MainWindow", "00"))
        self.equal_btn.setText(_translate("MainWindow", "="))
        self.plus_btn.setText(_translate("MainWindow", "+"))
        self.subtraction_btn.setText(_translate("MainWindow", "-"))
        self.division_btn.setText(_translate("MainWindow", "/"))
        self.multiplication_btn.setText(_translate("MainWindow", "x"))
        self.clear_btn.setText(_translate("MainWindow", "C"))
        self.back_btn.setText(_translate("MainWindow", "<"))
        # self.number_0.clicked.connect(lambda: self.number_press(self, "0"))
        self.number_0.clicked.connect(lambda: self.number_press("0"))
        self.number_00.clicked.connect(lambda: self.number_press("00"))
        self.number_1.clicked.connect(lambda: self.number_press("1"))
        self.number_2.clicked.connect(lambda: self.number_press("2"))
        self.number_3.clicked.connect(lambda: self.number_press("3"))
 # my codes:
        self.number_4.clicked.connect(lambda: self.number_press("4"))
        self.number_5.clicked.connect(lambda: self.number_press("5"))
        self.number_6.clicked.connect(lambda: self.number_press("6"))
        self.number_7.clicked.connect(lambda: self.number_press("7"))
        self.number_8.clicked.connect(lambda: self.number_press("8"))
        self.number_9.clicked.connect(lambda: self.number_press("9"))
        self.point_btn.clicked.connect(lambda: self.number_press("."))

        self.subtraction_btn.clicked.connect(lambda: self.operator_press("-")) 
        self.plus_btn.clicked.connect(lambda: self.operator_press("+"))
        self.division_btn.clicked.connect(lambda: self.operator_press("÷"))
        self.multiplication_btn.clicked.connect(lambda: self.operator_press("×"))
        
        self.back_btn.clicked.connect(self.back_press)

        self.clear_btn.clicked.connect(self.clear_press)
        self.equal_btn.clicked.connect(self.equal_press)
    #my functions:
    def number_press(self, number):
        expression = self.lineEdit.text()
        self.lineEdit.setText(expression + number)
    def convertListToString(self, myList):
        text = '' #رشته خالی

        for i in myList:
                text = text + str(i) + ""
        
        return text

    def operator_press(self, operator):
        expression = self.lineEdit.text()
        self.lineEdit.setText(expression + operator)
    def back_press(self):
        expression = self.lineEdit.text()
        if(len(expression) > 0):
                expression = expression[:-1]
                self.lineEdit.setText(str(expression))
    def clear_press(self):
        self.lineEdit.setText("") 
    def equal_press(self):
        try:
                expression = self.lineEdit.text()
                list_expression = list(expression)
                for n in list_expression:
                        if n == "×":
                                Index1 = list_expression.index(n)
                                list_expression[Index1] = "*"
                                expression = self.convertListToString(list_expression)
                        if n == "÷":
                                Index1 = list_expression.index(n)
                                list_expression[Index1] = "/"
                                expression = self.convertListToString(list_expression)
                print(expression)
                                
                
                result = eval(expression)
                self.lineEdit.setText(str(result))
        except:
                messagebox.showerror("eroor!!!", "expression is not valid!!!")  
                              

    
    
       

    
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
